const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("rengeDesktop", {
  isElectron: true,
  selectWorkspace: () => ipcRenderer.invoke("workspace:select"),
  selectSkillFolder: () => ipcRenderer.invoke("skill:select-folder"),
  restoreWorkspace: (options) => ipcRenderer.invoke("workspace:restore", options),
  listFiles: (options) => ipcRenderer.invoke("workspace:list", options),
  readFile: (options) => ipcRenderer.invoke("workspace:read", options),
  readBinaryFile: (options) => ipcRenderer.invoke("workspace:read-binary", options),
  readFileRange: (options) => ipcRenderer.invoke("workspace:read-range", options),
  fileInfo: (options) => ipcRenderer.invoke("workspace:info", options),
  searchFiles: (options) => ipcRenderer.invoke("workspace:search", options),
  writeFile: (options) => ipcRenderer.invoke("workspace:write", options),
  writeBinaryFile: (options) => ipcRenderer.invoke("workspace:write-binary", options),
  editFile: (options) => ipcRenderer.invoke("workspace:edit", options),
  createDirectory: (options) => ipcRenderer.invoke("workspace:mkdir", options),
  renamePath: (options) => ipcRenderer.invoke("workspace:rename", options),
  deletePath: (options) => ipcRenderer.invoke("workspace:delete", options),
  runScript: (options) => ipcRenderer.invoke("workspace:run-script", options),
  runCommand: (options) => ipcRenderer.invoke("workspace:run-command", options),
  gitStatus: () => ipcRenderer.invoke("workspace:git-status"),
  gitDiff: (options) => ipcRenderer.invoke("workspace:git-diff", options),
  detectStack: () => ipcRenderer.invoke("workspace:detect-stack"),
  searchRegex: (options) => ipcRenderer.invoke("workspace:search-regex", options),
  findSymbols: (options) => ipcRenderer.invoke("workspace:find-symbols", options),
  readPackageJson: () => ipcRenderer.invoke("workspace:package-json"),
  scanTodos: (options) => ipcRenderer.invoke("workspace:todos", options),
});
