/** Runtime source for the small STscript bridge exposed inside HTML previews. */
export const HTML_PREVIEW_STSCRIPT_COMPAT_SOURCE = [
  "const stScriptNormalizeKey = (value) => String(value ?? \"\").trim().replace(/^['\\\"]|['\\\"]$/g, \"\");",
  "const stScriptGetVariable = (key) => {",
  "  const normalizedKey = stScriptNormalizeKey(key);",
  "  if (!normalizedKey) return \"\";",
  "  const variables = getAllVariables();",
  "  return variables && variables[normalizedKey] !== undefined ? variables[normalizedKey] : \"\";",
  "};",
  "const stScriptSetVariable = async (key, value) => {",
  "  const normalizedKey = stScriptNormalizeKey(key);",
  "  if (!normalizedKey) return \"\";",
  "  const normalizedValue = String(value ?? \"\");",
  "  await insertOrAssignVariables({ [normalizedKey]: normalizedValue }, { type: \"chat\" });",
  "  return normalizedValue;",
  "};",
  "const stScript = async (command) => {",
  "  const parts = String(command ?? \"\").trim().split(/\\s*\\|\\s*(?=\\/)/).filter(Boolean);",
  "  let result = \"\";",
  "  for (const rawPart of parts) {",
  "    const part = rawPart.trim();",
  "    const sendMatch = /^\\/send\\b(?:\\s+([\\s\\S]*))?$/i.exec(part);",
  "    if (sendMatch) { result = await setInput(sendMatch[1] ?? \"\"); continue; }",
  "    if (/^\\/(?:trigger|gen)\\b/i.test(part)) { result = await sendMessage(getInput()); continue; }",
  "    const getMatch = /^\\/getvar\\b\\s*(?:key=)?\\s*([\\s\\S]*)$/i.exec(part);",
  "    if (getMatch) { result = stScriptGetVariable(getMatch[1]); continue; }",
  "    const setMatch = /^\\/setvar\\b\\s+(?:key=)?([^\\s]+)(?:\\s+([\\s\\S]*))?$/i.exec(part);",
  "    if (setMatch) { result = await stScriptSetVariable(setMatch[1], setMatch[2] ?? \"\"); continue; }",
  "    result = await triggerSlash(part);",
  "  }",
  "  return result;",
  "};",
  "if (typeof window.STscript !== \"function\") window.STscript = stScript;",
  "if (typeof window.stscript !== \"function\") window.stscript = window.STscript;",
].join("");
